# Generated by Django 4.2.7 on 2024-04-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.TextField(blank=True, db_column='Product Code', null=True)),
                ('product_description', models.TextField(blank=True, db_column='Product Description', null=True)),
                ('number_2022_rates', models.TextField(blank=True, db_column='2022 Rates', null=True)),
                ('number_2023_rates', models.TextField(blank=True, db_column='2023 Rates', null=True)),
                ('number_2024_rates', models.TextField(blank=True, db_column='2024 Rates', null=True)),
            ],
            options={
                'db_table': 'price_list',
                'managed': False,
            },
        ),
    ]
