# Generated by Django 4.2.7 on 2024-04-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_pricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.TextField(blank=True, db_column='Party Name', null=True)),
                ('po_date', models.TextField(blank=True, db_column='PO Date', null=True)),
                ('invoice_no', models.TextField(blank=True, db_column='Invoice No', null=True)),
                ('invoice_date', models.TextField(blank=True, db_column='Invoice Date', null=True)),
                ('product_code', models.TextField(blank=True, db_column='Product Code', null=True)),
                ('product_description', models.TextField(blank=True, db_column='Product Description', null=True)),
                ('specification', models.TextField(blank=True, db_column='Specification', null=True)),
                ('tariff_code', models.TextField(blank=True, db_column='Tariff Code', null=True)),
                ('pack_size', models.TextField(blank=True, db_column='Pack Size', null=True)),
                ('quantity', models.CharField(blank=True, db_column='Quantity', max_length=10, null=True)),
                ('uom', models.TextField(blank=True, db_column='UOM', null=True)),
                ('total_quantity', models.TextField(blank=True, db_column='Total Quantity', null=True)),
                ('currency', models.TextField(blank=True, db_column='Currency', null=True)),
                ('unit_price', models.TextField(blank=True, db_column='Unit Price', null=True)),
                ('total_amount', models.TextField(blank=True, db_column='Total Amount', null=True)),
                ('rate', models.TextField(blank=True, db_column='Rate', null=True)),
                ('unit_price_in_rs', models.TextField(blank=True, db_column='Unit Price In Rs', null=True)),
                ('tot_amt_rs_field', models.TextField(blank=True, db_column='Tot Amt Rs.', null=True)),
                ('cd', models.TextField(blank=True, db_column='CD', null=True)),
                ('igst', models.TextField(blank=True, db_column='IGST', null=True)),
                ('foreign_freight_excl_gst_field', models.TextField(blank=True, db_column='Foreign Freight\n ( Excl GST )', null=True)),
                ('ex_works_freight_uk_excl_gst_field', models.TextField(blank=True, db_column='Ex works Freight UK\n ( Excl GST)', null=True)),
                ('cha_charges_excl_gst_field', models.TextField(blank=True, db_column='CHA Charges\n(Excl GST)', null=True)),
                ('total_incl_b_e_igst_excl_cha_igst', models.TextField(blank=True, db_column='Total incl\nB/E IGST  Excl CHA IGST', null=True)),
                ('unit_landed_cost_rs_col_24_col_12', models.TextField(blank=True, db_column='Unit Landed Cost (Rs.)\nCol 24/col 12', null=True)),
                ('b_e_gross_weight_kgs', models.TextField(blank=True, db_column='B/E Gross weight Kgs', null=True)),
                ('field_f_freight_ex_works_freight_cha_charges_gw', models.TextField(blank=True, db_column='(F  Freight+ Ex Works Freight+CHA charges)/\nGW', null=True)),
            ],
            options={
                'db_table': 'supplier_invoice',
                'managed': False,
            },
        ),
    ]
