# Generated by Django 4.2.7 on 2024-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductMaster',
            fields=[
                ('prod_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('supp_id', models.CharField(max_length=4)),
                ('prod_desc', models.CharField(blank=True, max_length=75, null=True)),
                ('spec_id', models.CharField(blank=True, max_length=4, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'supplier_product_master',
                'managed': False,
            },
        ),
    ]
