# Generated by Django 4.2.7 on 2025-08-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('cust_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_addr1', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_addr2', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_city', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_st_code', models.IntegerField(blank=True, null=True)),
                ('cust_st_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('cust_gst_id', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_name_1', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_phone_1', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email_1', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_name_2', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email_2', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_exemption', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Customer_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalPo',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('pono', models.CharField(max_length=100)),
                ('podate', models.DateField(blank=True, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=15, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.CharField(max_length=15)),
                ('consignee_id', models.CharField(blank=True, max_length=15, null=True)),
                ('po_sl_no', models.CharField(max_length=5)),
                ('prod_code', models.CharField(blank=True, max_length=30, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('omat', models.CharField(blank=True, max_length=50, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uom', models.CharField(blank=True, max_length=5, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_sent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('po_validity', models.DateField(blank=True, null=True)),
                ('gst_applicable', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'final_po',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GstRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst_rate', models.IntegerField(blank=True, null=True)),
                ('sgst_rate', models.IntegerField(blank=True, null=True)),
                ('igst_rate', models.IntegerField(blank=True, null=True)),
                ('fin_year', models.IntegerField(blank=True, null=True)),
                ('last_gcn_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GstStateCode',
            fields=[
                ('state_code', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'gst_state_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierProductMaster',
            fields=[
                ('prod_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('supp_id', models.CharField(blank=True, max_length=30, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('spec_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'supplier_product_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtwDc',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('gcn_no', models.CharField(blank=True, max_length=20, null=True)),
                ('gcn_date', models.DateField(blank=True, null=True)),
                ('po_no', models.CharField(blank=True, max_length=15, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('consignee_id', models.CharField(blank=True, max_length=10, null=True)),
                ('prod_id', models.CharField(blank=True, max_length=15, null=True)),
                ('po_sl_no', models.CharField(blank=True, max_length=10, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('omat', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_delivered', models.TextField(blank=True, null=True)),
                ('pack_size', models.TextField(blank=True, null=True)),
                ('unit_price', models.TextField(blank=True, null=True)),
                ('taxable_amt', models.TextField(blank=True, null=True)),
                ('cgst_price', models.TextField(blank=True, null=True)),
                ('sgst_price', models.TextField(blank=True, null=True)),
                ('igst_price', models.TextField(blank=True, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=10, null=True)),
                ('batch', models.CharField(blank=True, max_length=10, null=True)),
                ('coc', models.CharField(blank=True, max_length=10, null=True)),
                ('batch_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_exemption', models.BooleanField(blank=True, null=True)),
                ('location', models.CharField(default='HBL', max_length=3)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='purchase_order.customermaster')),
            ],
            options={
                'db_table': 'otw_dc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomerPurchaseOrder',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('pono', models.TextField(blank=True, null=True)),
                ('podate', models.DateField(blank=True, null=True)),
                ('quote_id', models.TextField(blank=True, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('consignee_id', models.TextField(blank=True, null=True)),
                ('po_sl_no', models.TextField(blank=True, null=True)),
                ('prod_code', models.TextField(blank=True, null=True)),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('additional_desc', models.TextField(blank=True, null=True)),
                ('pack_size', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('uom', models.TextField(blank=True, null=True)),
                ('hsn_sac', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('qty_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('qty_sent', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('po_validity', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='HBL', max_length=3)),
                ('cust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase_order.customermaster')),
            ],
            options={
                'db_table': 'Customer_Purchase_Order',
                'managed': True,
            },
        ),
    ]
