# Generated by Django 4.2.7 on 2025-08-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otwdc',
            name='location',
            field=models.CharField(default='HBL', max_length=3),
        ),
    ]