# Generated by Django 4.2.7 on 2024-05-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('cust_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_addr1', models.CharField(blank=True, max_length=30, null=True)),
                ('cust_addr2', models.CharField(blank=True, max_length=30, null=True)),
                ('cust_city', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_st_code', models.IntegerField(blank=True, null=True)),
                ('cust_st_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('cust_gst_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=30)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_validity', models.DateField(blank=True, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=15, null=True)),
                ('cust_id', models.CharField(max_length=15)),
                ('consignee_id', models.CharField(blank=True, max_length=15, null=True)),
                ('po_sl_no', models.CharField(blank=True, max_length=5, null=True)),
                ('prod_id', models.CharField(max_length=30)),
                ('prod_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('msrr', models.CharField(blank=True, max_length=50, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('staggered_delivery', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('qty_sent', models.IntegerField(blank=True, null=True)),
                ('qty_bal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_purchase_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustPo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('po_validity', models.DateField(blank=True, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_id', models.CharField(blank=True, max_length=30, null=True)),
                ('consignee_id', models.CharField(blank=True, max_length=30, null=True)),
                ('po_sl_no', models.CharField(blank=True, max_length=15, null=True)),
                ('prod_id', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('msrr', models.CharField(blank=True, max_length=100, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('staggered_deliver', models.CharField(blank=True, max_length=45, null=True)),
                ('unit_price', models.CharField(blank=True, max_length=20, null=True)),
                ('qty_sent', models.CharField(blank=True, max_length=15, null=True)),
                ('qty_bal', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'cust_po',
                'managed': False,
            },
        ),
    ]
