# Generated by Django 4.2.7 on 2024-05-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_customermaster_customerpurchaseorder_custpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustPo',
        ),
        migrations.AlterModelTable(
            name='customermaster',
            table='Customer_Master',
        ),
    ]
