# Generated by Django 4.2.7 on 2025-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_auto_20250809_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchaseorder',
            name='location',
            field=models.CharField(default='HBL', max_length=3),
        ),
    ]