# Generated by Django 4.2.7 on 2024-05-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_alter_customerpurchaseorder_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst_rate', models.IntegerField(blank=True, null=True)),
                ('sgst_rate', models.IntegerField(blank=True, null=True)),
                ('igst_rate', models.IntegerField(blank=True, null=True)),
                ('fin_year', models.IntegerField(blank=True, null=True)),
                ('last_gcn_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GstStateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.IntegerField(blank=True, null=True)),
                ('state_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_state_code',
                'managed': False,
            },
        ),
    ]
