# Generated by Django 4.2.7 on 2024-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_gstrates_gststatecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtwDc',
            fields=[
                ('gcn_no', models.TextField(primary_key=True, serialize=False)),
                ('gcn_date', models.TextField(blank=True, null=True)),
                ('po_no', models.TextField()),
                ('po_date', models.TextField(blank=True, null=True)),
                ('cust_id', models.TextField(blank=True, null=True)),
                ('consignee_id', models.TextField(blank=True, null=True)),
                ('prod_id', models.TextField(blank=True, null=True)),
                ('po_sl_no', models.TextField()),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('additional_desc', models.TextField(blank=True, null=True)),
                ('qty_delivered', models.TextField(blank=True, null=True)),
                ('pack_size', models.TextField(blank=True, null=True)),
                ('unit_price', models.TextField(blank=True, null=True)),
                ('taxable_amt', models.TextField(blank=True, null=True)),
                ('cgst_price', models.TextField(blank=True, null=True)),
                ('sgst_price', models.TextField(blank=True, null=True)),
                ('igst_price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otw_dc',
                'managed': False,
            },
        ),
    ]
