# Generated by Django 5.0.6 on 2024-07-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPo',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('pono', models.CharField(max_length=100)),
                ('podate', models.DateField(blank=True, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=15, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.CharField(max_length=15)),
                ('consignee_id', models.CharField(blank=True, max_length=15, null=True)),
                ('po_sl_no', models.CharField(max_length=5)),
                ('prod_code', models.CharField(blank=True, max_length=30, null=True)),
                ('prod_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('omat', models.CharField(blank=True, max_length=50, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uom', models.CharField(blank=True, max_length=5, null=True)),
                ('hsn_sac', models.CharField(blank=True, max_length=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty_sent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('po_validity', models.DateField(blank=True, null=True)),
                ('gst_applicable', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'final_po',
                'managed': False,
            },
        ),
    ]
