# Generated by Django 5.0.6 on 2025-02-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0008_finalpo'),
    ]

    operations = [
    ]
